########################################################################
# 1. Base 50 MHz input clock from the DE2-115 board
########################################################################
# CLOCK_50 is the primary 50 MHz clock input provided by the board.
create_clock -name CLOCK_50 -period 20.000 [get_ports {CLOCK_50}]
derive_pll_clocks
derive_clock_uncertainty


########################################################################
# 2. PLL-generated 100 MHz fast clock
########################################################################
# Instance: u_pll (entity: PLL_clock_top)
#   Input  port : clock_50MHz
#   Output port : clock_100Mhz
#
# The PLL multiplies the 50 MHz input clock by 2 to generate 100 MHz.
# If the PLL configuration is changed later, update the -multiply_by
# value accordingly.

create_generated_clock \
    -name CLK_FAST \
    -multiply_by 2 \
    -source [get_ports {CLOCK_50}] \
    [get_pins {tank_duel_top|u_pll|clock_100Mhz}]


########################################################################
# 3. VGA pixel clock (generated inside vga_sync_pipe)
########################################################################
# Instance: u_sync (entity: vga_sync_pipe)
#   Input  port : clock_50mhz
#   Output port: pixel_clock
#
# The pixel clock is generated by dividing the 50 MHz input clock by 2,
# resulting in a ~25 MHz VGA pixel clock.
# If you later switch to a PLL-generated pixel clock, modify the
# -source and target pin accordingly.

create_generated_clock \
    -name PIXEL_CLK \
    -divide_by 2 \
    -source [get_ports {CLOCK_50}] \
    [get_pins {tank_duel_top|u_sync|pixel_clock}]


########################################################################
# 4. Asynchronous reset (exclude from timing analysis)
########################################################################
# RESET_N is an asynchronous reset and should not be treated as part
# of synchronous timing paths. Mark it as a false path.

set_false_path -from [get_ports {RESET_N}]


########################################################################
# 5. PS/2 interface — treated as asynchronous external signals
########################################################################
# PS/2 clock and data come from an external keyboard and do not belong
# to any internal synchronous clock domain. Without a proper external
# clock model, they are better excluded to avoid meaningless timing
# violations.

set_false_path -from [get_ports {PS2_CLK}]
set_false_path -from [get_ports {PS2_DAT}]


########################################################################
# 6. I/O output timing (optional)
########################################################################
# For a project where the main goal is verifying internal timing
# (CLOCK_50 / CLK_FAST / PIXEL_CLK domains), it is acceptable to omit
# explicit output delay constraints for VGA or 7-segment displays.
# Quartus will still analyze internal clock-to-output timing.
#
# If precise timing modeling for the VGA monitor is required, define
# a virtual external clock and apply set_output_delay constraints.
# This is optional for typical course projects.